# replication
replicaCount: 1
# pod node selector
nodeSelector: {}
# pod toleration
tolerations: []
#pod DNS policy and config
podDnsPolicy: "None"
podDnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4

#motechat einame
MCHAT_EINAME: fbots-example
#motechat appname
MCHAT_APPNAME: fbots-example-app
#motechat motebus gateway
MCHAT_MBGWIP: "127.0.0.1"
#motechat dc
MCHAT_DC: dc
#motechat ioc
MCHAT_IOC: ioc
# motechat send timeout
MCHAT_SENDTIMEOUT: "6"
# motechat send reply timeout
MCHAT_WAITREPLY: "12"
# make MCHAT_EINAME = MCHAT_EINAME-MCHAT_UDID
MCHAT_UDID: "1"
# motecaht log level
MCAHT_WATCHLEVEL: "3"
#fbots mode, "local, xstorage"
FBOT_MODE: xstorage
# qcode of flow
FBOT_QCODE:
# qname of flow
FBOT_QNAME:
# number of instance
FBOT_MANY: "1"
# ui enable="1" disable="0"
FBOT_UI: "1"
# set FBOT_PORT=188, will change to 18800, 18801, ... (FBOT_MANY > 1)
FBOT_PORT: 1880
# Make different instances have different MCHAT_EINAME and MCHAT_APPNAME (FBOT_MANY > 1)
FBOT_MULTI: 0
# Make different instances have different MCHAT_APPNAME, but have same MCHAT_EINAME (FBOT_MANY > 1)
FBOT_CLUSTER: 0
# motebus upstream
MBSTACK_UPSTREAM: h3.ypcloud.com
# motebus bus mode
MBSTACK_BUSMODE: 0
# motebus watch level
MBSTACK_WATCHLEVEL: 3
# motebus bus name
MBSTACK_BUSNAME:
# motebus volume
MBSTACK_DATAPATH: /var/motebus
# motebus ip finder
MBSTACK_IPFINDER: "auto"
#timezone
timezone: Asia/Taipei

fbots:
  # image settings and pull policy
  image:
    repository: motebus/fbots
    tag: v1.1.1
    pullPolicy: IfNotPresent
  # service settings
  service:
    type: ClusterIP
    protocol: TCP
    nodePort:
    port: 1880
  # configuration settings
  container:
    # fbots port
    port: 1880
    #extra envs
    extraEnvs: {}
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: "kong"
      konghq.com/strip-path: "true"
      konghq.com/override: "https-only"
    tls:
      []
      # - hosts:
      #     - myapps.ypcloud.com
      #   secretName: fbots-tls
    hosts:
      []
      # - myapps.ypcloud.com
    path: /fbots/(.*)
    pathType: Prefix
  persistence:
    #Enable config persistence using PVC
    enabled: false
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 100Mi
    # ingress host and path

motebus:
  image:
    repository: motebus/motebus
    tag: latest
    pullPolicy: Always
  persistence:
    #Enable config persistence using PVC
    enabled: true
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 100Mi
