# ingress host and path
ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls: []
    # - hosts:
    #     - myapps.ypcloud.com
    #   secretName: fbots-tls
  hosts: []
    # - myapps.ypcloud.com
  path: /fbots/(.*)
  pathType: Prefix

# container env settings
container:
  # fbots port
  port: 1880
  #extra envs
  extraEnvs: {}

# replication
replicaCount: 1

#container image settings and pull policy
image:
  repository:
    motebus: motebus/motebus
    fbots: motebus/fbots
  tag:
    motebus: latest
    fbots: v1.1.0
  pullPolicy:
    motebus: Always
    fbots: Always

# service settings
service:
  type: ClusterIP
  protocol: TCP
  nodePort:
  port: 1880

# pod node selector
nodeSelector: {}

persistence:
  #Enable config persistence using PVC
  enabled: true
  # PVC Access Mode for config volume
  accessMode: ReadWriteOnce
  # PVC Storage Class for config volume
  storageClass: nfs
  # PVC Storage Request for config volume
  size: 1Gi

#motechat ei name
MCHAT_EINAME: fbots-example
#motechat motebus gateway
MCHAT_MBGWIP: 127.0.0.1
#motechat dc
MCHAT_DC: dc
#motechat ioc
MCHAT_IOC: ioc
# motechat send timeout
MCHAT_SENDTIMEOUT: "6"
# motechat send reply timeout
MCHAT_WAITREPLY: "12"
# make MCHAT_EINAME = MCHAT_EINAME-MCHAT_UDID
MCHAT_UDID: 1
#fbots mode, "local, xstorage"
FBOT_MODE: xstorage
# qcode of flow
FBOT_QCODE:
# qname of flow
FBOT_QNAME:
# number of instance
FBOT_MANY: 1
# Make different instances have different MCHAT_EINAME and MCHAT_APPNAME (FBOT_MANY > 1)
FBOT_MULTI: 0 
# Make different instances have different MCHAT_APPNAME, but have same MCHAT_EINAME (FBOT_MANY > 1)
FBOT_CLUSTER: 0
# motebus upstream
MBSTACK_UPSTREAM: h3.ypcloud.com
# motebus bus mode
MBSTACK_BUSMODE: 0
# motebus watch level
MBSTACK_WATCHLEVEL: 3
# motebus bus name
MBSTACK_BUSNAME:
# motebus volume
MBSTACK_DATAPATH: /var/motebus
# motebus ip finder
MBSTACK_IPFINDER: "auto"
#timezone
timezone: Asia/Taipei

#pod DNS policy and config
podDnsPolicy: "None"
podDnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4
