ingress:
  host: myapps.ypcloud.com
  path: /

host:
  path:
    motebus: /var/motebus/
    flowbot: /var/motebus/flow/

pod:
  name: mpod-

mbstack:
  upstream: uc.ypcloud.com,boss.ypcloud.com
  aliases: uc=oss/uc;ioc=boss/ioc

replicaCount: 1

image:
  repository:
    flowbot: motebus/flowbot:latest
    motebus: motebus/motebus:v2.4.8
    fbuilder: motebus/fbuilder:latest
    page: motebus/page-hellow:latest
  pullPolicy: Always

service:
  type: ClusterIP
  protocol: TCP
