# nginx-ingress-control annotation ssl redirect
enabledSslRedirect: false

# chart namespace
namespace: default

# ingress host and path
ingress:
  enabled: true
  host: myapps.ypcloud.com
  path: /iocview

# container
container:
    # container port
    port: 8083

# replication
replicaCount: 1

# container images
image:
  repository:
    motebus: motebus/motebus:latest
    iocview: motebus/iocview:latest
  pullPolicy: 
    motebus: Always
    iocview: Always

# service settings
service:
  type: ClusterIP
  nodePort: 
  protocol: TCP
  port: 80

# pod node selector
nodeSelector: {}


#motechat motebus gateway
MCHAT_MBGWIP: 127.0.0.1
#motechat motebus gateway port
MCHAT_MBGWPORT: 6262
#motechat dc
MCHAT_DC: dc
#motechat watch level
MCAHT_WATCHLEVEL: 1
#motechat ei name
MCHAT_EINAME: ioc
#motechat app name
MCHAT_APPNAME: ioc-svc
#motebus bus mode
MBSTACK_BUSMODE: 0
#motebus bus name
MBSTACK_BUSNAME: ioc
#motebus upstream
MBSTACK_UPSTREAM: gke.ypcloud.com


#timezone
timezone: Asia/Taipei