apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector}}
{{- end }}
      containers:
        - name: miki
          image: {{ .Values.image.repository.miki}}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: MCHAT_MBGWIP
              value: {{ .Values.MCHAT_MBGWIP}}
            - name: MCHAT_DC
              value: {{ .Values.MCHAT_DC}}
            - name: MCHAT_APPNAME
              value: {{ .Values.MCHAT_EINAME}}-app
            - name: MCHAT_EINAME
              value: {{ .Values.MCHAT_EINAME}}
            - name: MCHAT_MBPORT
              value: {{ .Values.MCHAT_MBPORT | quote}}
            - name: PORT
              value: {{ .Values.container.port | quote }}
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.MINIO_ACCESS_KEY}}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.MINIO_SECRET_KEY}}
            - name: MINIO_ENDPOINT
              value: {{ .Values.MINIO_ENDPOINT}}
            - name: MINIO_PORT
              value: {{ .Values.MINIO_PORT | quote}}
            - name: IP
              value: {{ .Values.IP}}
            - name: NODE_ENV
              value: production
            - name: PUBLIC_URL
              value: '/'
          ports:
           - name: miki-port
             containerPort: {{ .Values.container.port}}
          imagePullPolicy: {{ .Values.image.pullPolicy.miki}}
          volumeMounts:
            - name: miki-tz
              mountPath: /etc/localtime

        - name: motebus
          image: {{ .Values.image.repository.motebus}}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: MBSTACK_BUSMODE
              value: {{ .Values.MBSTACK_BUSMODE | quote}}
            - name: MBSTACK_UPSTREAM
              value: {{.Values.MBSTACK_UPSTREAM}}
          imagePullPolicy: {{ .Values.image.pullPolicy.motebus}}
          volumeMounts:
            - name: motebus-tz
              mountPath: /etc/localtime

      volumes:
        - name: miki-tz
          hostPath: 
            path: /etc/localtime
        - name: motebus-tz
          hostPath: 
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port}}
      targetPort: miki-port

