apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.pod.name}}{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector}}
{{- end }}
      containers:
        - name: aibot
          image: {{ .Values.image.repository.aibot}}
          env:
            - name: MOTEBUS_GATEWAY
              value: 127.0.0.1
            - name: DC
              value: dc
          imagePullPolicy: {{ .Values.image.pullPolicy}}

        - name: motebus
          image: {{ .Values.image.repository.motebus}}
          env:
            - name: MBSTACK_BUSMODE
              value: "0"
            - name: MBSTACK_BUSNAME
              value: mpod
            - name: MBSTACK_UPSTREAM
              value: {{.Values.mbstack.upstream}}
            - name: MBSTACK_ALIASES
              value: {{.Values.mbstack.aliases}}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
            


