apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ .Release.Name }}-http-log
config: 
  {{- $jupyterIngressPath := .Values.jupyter.ingress.path -}}
    {{- range .Values.jupyter.ingress.hosts }}
  http_endpoint: {{ . }}{{ $jupyterIngressPath }}
  {{- end }}
  method: POST
  timeout: 1000
  keepalive: 1000
  flush_timeout: 2
  retry_count: 15
plugin: http-log