apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- if .Values.podDnsPolicy}}
      dnsPolicy: {{ .Values.podDnsPolicy}}
{{- end}}
{{- if .Values.podDnsConfig}}
      dnsConfig:
{{ toYaml .Values.podDnsConfig | indent 8}}
{{- end}}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: jupyter
          image: {{ .Values.jupyter.image.repository }}:{{ .Values.jupyter.image.tag }}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: BASE_URL
              value: {{ .Values.BASE_URL }}
{{- if .Values.jupyter.container.extraEnvs }}
{{ toYaml .Values.jupyter.container.extraEnvs | indent 12 }}
{{- end }}
          ports:
           - name: jupyter-port
             containerPort: {{ .Values.jupyter.container.port}}
           - name: mlflow-port
             containerPort: {{ .Values.mlflow.container.port}}
          imagePullPolicy: {{ .Values.jupyter.image.pullPolicy}}
          volumeMounts:
            - name: jupyter-vol
              mountPath: /home
            - name: tz
              mountPath: /etc/localtime

      volumes:
        - name: tz
          hostPath:
            path: /etc/localtime             

  volumeClaimTemplates:
{{- if .Values.jupyter.persistence.enabled}}
    - metadata:
        name: jupyter-vol
      spec:
        accessModes:  [ {{ .Values.jupyter.persistence.accessMode | quote }} ]
        storageClassName: {{ .Values.jupyter.persistence.storageClass | quote }}
        resources:
            requests:
                storage: {{ .Values.jupyter.persistence.size | quote }}
{{- end}}