apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.jupyter.service.type }}
  selector:
    app: {{ .Release.Name }}-deployment
{{- if eq .Values.jupyter.service.type "ClusterIP"}}
  clusterIP: None
{{- end}}
  ports:
    - name: jupyter-port
      protocol: {{ .Values.jupyter.service.protocol }}
{{- if eq .Values.jupyter.service.type "NodePort"}}
      nodePort: {{ .Values.jupyter.service.nodePort}}
{{- end}}
      port: {{ .Values.jupyter.service.port}}
      targetPort: {{ .Values.NB_PORT}}
{{- if .Values.swagger.enabled}}
    - name: swagger-port
      protocol: {{ .Values.swagger.service.protocol }}
{{- if eq .Values.swagger.service.type "NodePort"}}
      nodePort: {{ .Values.swagger.service.nodePort}}
{{- end}}
      port: {{ .Values.swagger.service.port}}
      targetPort: {{ .Values.SERVICE_PORT}}
{{- end}}
