apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-deployment
{{- if eq .Values.service.type "ClusterIP"}}
  clusterIP: None
{{- end}}
  ports:
    - name: jupyter-port
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.jupyter.service.port}}
      targetPort: jupyter-port
    - name: mlflow-port
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.mlflow.service.port}}
      targetPort: mlflow-port