apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector}}
{{- end }}
      containers:
        - name: iocview
          image: {{ .Values.image.repository.iocview}}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: MCHAT_MBGWIP
              value: {{ .Values.MCHAT_MBGWIP}}
            - name: MCHAT_DC
              value: {{ .Values.MCHAT_DC}}
            - name: MCHAT_MBGWPORT
              value: {{ .Values.MCHAT_MBGWPORT | quote}}
            - name: MCAHT_WATCHLEVEL
              value: {{ .Values.MCAHT_WATCHLEVEL | quote}}
            - name: MCHAT_EINAME
              value: {{ .Values.MCHAT_EINAME}}
            - name: MCHAT_APPNAME
              value: {{ .Values.MCHAT_APPNAME}}
          ports:
           - name: iocview-port
             containerPort: {{ .Values.container.port}}
          imagePullPolicy: {{ .Values.image.pullPolicy.iocview}}
          volumeMounts:
            - name: iocview-tz
              mountPath: /etc/localtime

        - name: motebus
          image: {{ .Values.image.repository.motebus}}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: MBSTACK_BUSMODE
              value: {{ .Values.MBSTACK_BUSMODE | quote}}
            - name: MBSTACK_BUSNAME
              value: {{ .Values.MBSTACK_BUSNAME }}
            - name: MBSTACK_UPSTREAM
              value: {{ .Values.MBSTACK_UPSTREAM }}
          imagePullPolicy: {{ .Values.image.pullPolicy.motebus}}
          volumeMounts:
            - name: motebus-tz
              mountPath: /etc/localtime
    
      volumes:
        - name: iocview-tz
          hostPath: 
            path: /etc/localtime
        - name: motebus-tz
          hostPath: 
            path: /etc/localtime
            
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port}}
      targetPort: iocview-port

