{{- if .Values.mlflow.ingress.enabled}}
{{- $ingressPath := .Values.mlflow.ingress.path -}}
{{- $servicePort := .Values.mlflow.service.port -}}
{{- $releaseName := .Release.Name -}}
{{- $ingressPathType := .Values.mlflow.ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
{{- if .Values.mlflow.ingress.https }}
  tls:
    - hosts:
      - {{ .Values.mlflow.ingress.hostName }}
      secretName: {{ .Values.mlflow.ingress.hostName }}-tls
{{- end }}
  rules:
    - host: {{ .Values.mlflow.ingress.hostName }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $releaseName }}
                port:
                  number: {{ $servicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
{{- if .Values.mlflow.ingress.https }}
  tls:
    - hosts:
      - {{ .Values.mlflow.ingress.hostName }}
      secretName: {{ .Values.mlflow.ingress.hostName }}-tls
{{- end }}
  rules:
    - host: {{ .Values.mlflow.ingress.hostName }}
      http:
        paths:
          - path: {{ $ingressPath }}/api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $releaseName }}
                port:
                  number: {{ $servicePort }}
{{- end}}