# pod node selector
nodeSelector: {}
# replication
replicaCount: 1
# pod toleration
tolerations: []
# pod DNS policy and config

# podDnsPolicy: "None"
# podDnsConfig:
#   nameservers:
#     - 8.8.8.8
#     - 8.8.4.4

# s3 endpoint url
MLFLOW_S3_ENDPOINT_URL:
# aws acces key
AWS_ACCESS_KEY_ID:
# aws secret key
AWS_SECRET_ACCESS_KEY:
# mysql db uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@127.0.0.1:3306/${MYSQL_DATABASE}
DB_URI:
# s3 uri "s3://bucket"
ARTIFACT_URI:
# mlflow ui path
MLFLOW_STATIC_PREFIX:

mlflow:
  image:
    repository: motebus/mlflow
    tag: 2.6.0
    pullPolicy: IfNotPresent
  # container env settings
  container:
    #extra envs
    extraEnvs: {}
  service:
    type: ClusterIP
    protocol: TCP
    nodePort:
    port: 5000
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
    tls:
      - hosts:
        - apps.ypcloud.com
        secretName: apps.ypcloud.com-tls
    hosts:
      - apps.ypcloud.com
    path: /mlflow
    pathType: Prefix
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1024Mi
      cpu: 500m
