# nginx-ingress-control annotation ssl redirect
enabledSslRedirect: false

# UI
enabledUI: true

# chart namespace
namespace: default 

# ingress host and path
ingress:
  host: myapps.ypcloud.com
  path: /flowbot
  pathName: 

# container env settings
container:
    #extra envs
    extraEnvs: {}

# replication
replicaCount: 1

# docker image and pull policy
image:
  repository:
    motebus: motebus/motebus:latest
    flowbot: motebus/flowbot:latest
  pullPolicy: 
    motebus: Always
    flowbot: Always

# service settings
service:
  type: ClusterIP
  protocol: TCP
  port: 80

# pod node selector
nodeSelector: {}

# flowbot id
FBOT_FLOWID: 99999
# flowbot mode
FBOT_MODE: local
# flowbot port
FBOT_PORT: 1880
# flowbot ui
FBOT_UI: "1"
# motechat ei name
MCHAT_EINAME: flowbot-example
# motechat motebus gateway
MCHAT_MBGWIP: 127.0.0.1
# motechat dc
MCHAT_DC: dc
# motechat ioc 
MCHAT_IOC: ioc
# motechat motebus gatway port
MCHAT_MBGWPORT: "6262"
# motebus upstream
MBSTACK_UPSTREAM: gke.ypcloud.com
# motebus bus mode
MBSTACK_BUSMODE: 0
# motebus bus name
MBSTACK_BUSNAME: 
# motebus volume
MBSTACK_DATAPATH: /var/motebus

#timezone
timezone: Asia/Taipei


# persistent
persistence:
    #Enable config persistence using PVC
    enabled: true
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 1Gi