enabledHttpsBackendProtocol: false
enabledSslRedirect: false

namespace: default 
ui:
    enabled: true

ingress:
  host: myapps.ypcloud.com
  path: /flowbot/

container:
    einame: flowbot-exmaple
    motebusGateway: 127.0.0.1
    dc: dc
    port: 18888

mbstack:
  upstream: gke.ypcloud.com


replicaCount: 1

image:
  repository:
    motebus: motebus/motebus:v2.4.8
    flowbot: motebus/flowbot:v1.4.6
  pullPolicy: 
    motebus: IfNotPresent
    flowbot: IfNotPresent

service:
  type: ClusterIP
  protocol: TCP
  port: 80

nodeSelector: {}