{{- if eq .Values.kind "Deployment"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- if .Values.podDnsPolicy}}
      dnsPolicy: {{ .Values.podDnsPolicy}}
{{- end}}
{{- if .Values.podDnsConfig}}
      dnsConfig:
{{ toYaml .Values.podDnsConfig | indent 8}}
{{- end}}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: fbuilder
          image: {{ .Values.fbuilder.image.repository }}:{{ .Values.fbuilder.image.tag }}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: USER_MODE
              value: {{ .Values.USER_MODE }}
            - name: STORAGE_MODE
              value: {{ .Values.STORAGE_MODE }}
            - name: FB_PROJECT_ENABLE
              value: {{ .Values.FB_PROJECT_ENABLE | quote}}
            - name: FB_QOCIMAN
              value: {{ .Values.FB_QOCIMAN | quote}}
            - name: FB_OBJSTORE
              value: {{ .Values.FB_OBJSTORE | quote}}
            - name: FB_QMAN_DDN
              value: {{ .Values.FB_QMAN_DDN | quote}}
            - name: FB_ACCOUNT_MODE
              value: {{ .Values.FB_ACCOUNT_MODE | quote}}
            - name: FB_ACCOUNT_URL
              value: {{ .Values.FB_ACCOUNT_URL | quote}}
            - name: FB_ACCOUNT_LOGIN
              value: {{ .Values.FB_ACCOUNT_LOGIN | quote}}
            - name: FB_ACCOUNT_LOGOUT
              value: {{ .Values.FB_ACCOUNT_LOGOUT | quote}}
            - name: MCHAT_DC
              value: {{ .Values.MCHAT_DC}}
            - name: MCHAT_MBGWIP
              value: {{ .Values.MCHAT_MBGWIP | quote}}
            - name: MCHAT_MBGWPORT
              value: {{ .Values.MCHAT_MBGWPORT | quote}}
            - name: MCHAT_APPNAME
              value: {{ .Values.MCHAT_APPNAME }}
            - name: MCHAT_EINAME
              value: {{ .Values.MCHAT_EINAME }}
            - name: MCHAT_IOC
              value: {{ .Values.MCHAT_IOC }}
            - name: MCHAT_SENDTIMEOUT
              value: {{ .Values.MCHAT_SENDTIMEOUT }}
            - name: MCHAT_WAITREPLY
              value: {{ .Values.MCHAT_WAITREPLY }}
            - name: MCAHT_WATCHLEVEL
              value: {{ .Values.MCAHT_WATCHLEVEL | quote}}
{{- if .Values.fbuilder.container.extraEnvs }}
{{ toYaml .Values.fbuilder.container.extraEnvs | indent 12 }}
{{- end }}
          ports:
           - containerPort: {{ .Values.fbuilder.container.port}}
          imagePullPolicy: {{ .Values.fbuilder.image.pullPolicy}}
          volumeMounts:
            - name: tz
              mountPath: /etc/localtime

      volumes:
        - name: tz
          hostPath:
            path: /etc/localtime
{{- end }}