{{- if eq .Values.kind "Deployment"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: fbuilder
          image: {{ .Values.image.repository.fbuilder}}
          env:
            - name: MCHAT_EINAME
              value: {{ .Values.MCHAT_EINAME }}
            - name: MCHAT_APPNAME
              value: {{ .Values.MCHAT_EINAME }}-app
            - name: MCHAT_MBGWIP
              value: {{ .Values.MCHAT_MBGWIP}}
            - name: MCHAT_DC
              value: {{ .Values.MCHAT_DC}}
            - name: USER_MODE
              value: {{ .Values.USER_MODE}}
            - name: STORAGE_MODE
              value: {{ .Values.STORAGE_MODE}}
            - name: PORT
              value: {{ .Values.container.port | quote}}
{{- if .Values.container.extraEnvs }}
{{ toYaml .Values.container.extraEnvs | indent 12 }}
{{- end }}
          ports:
           - name: fbuilder-port
             containerPort: {{ .Values.container.port}}
          imagePullPolicy: {{ .Values.image.pullPolicy.fbuilder}}

        - name: motebus
          image: {{ .Values.image.repository.motebus}}
          env:
            - name: MBSTACK_BUSMODE
              value: {{.Values.MBSTACK_BUSMODE | quote}}
            - name: MBSTACK_UPSTREAM
              value: {{.Values.MBSTACK_UPSTREAM}}
            - name: MBSTACK_WATCHLEVEL
              value: {{.Values.MBSTACK_WATCHLEVEL}}
          imagePullPolicy: {{ .Values.image.pullPolicy.motebus}}
{{- end}}