apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
{{- if .Values.enabledSslRedirect }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
spec:
  rules:
    #對外訪問的域名
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: /fbuilder/(.*)
            backend:
              serviceName: {{ .Release.Name }}
              servicePort: http