apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: "nginx"
{{- if .Values.enabledHttpsBackendProtocol }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
{{- end }}
{{- if .Values.enabledSslRedirect }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
spec:
  tls:
    - hosts:
        - {{.Values.ingress.host}}
      secretName: {{ .Release.Name}}-tls
  rules:
    #對外訪問的域名
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: {{.Values.ingress.path}}{{ .Release.Name }}/(.*)
            backend:
              serviceName: {{ .Release.Name }}
              servicePort: {{ .Values.service.port}}