apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- if .Values.podDnsPolicy}}
      dnsPolicy: {{ .Values.podDnsPolicy}}
{{- end}}
{{- if .Values.podDnsConfig}}
      dnsConfig:
{{ toYaml .Values.podDnsConfig | indent 8}}
{{- end}}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: fbuilder
          image: {{ .Values.fbuilder.image.repository }}:{{ .Values.fbuilder.image.tag }}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: MCHAT_EINAME
              value: {{ .Values.MCHAT_EINAME }}
            - name: MCHAT_APPNAME
              value: {{ .Values.MCHAT_EINAME }}-app
            - name: MCHAT_MBGWIP
              value: {{ .Values.MCHAT_MBGWIP | quote}}
            - name: MCHAT_MBGWPORT
              value: {{ .Values.MCHAT_MBGWPORT | quote}}
            - name: MCAHT_WATCHLEVEL
              value: {{ .Values.MCAHT_WATCHLEVEL | quote}}
            - name: MCHAT_DC
              value: {{ .Values.MCHAT_DC}}
{{- if .Values.fbuilder.container.extraEnvs }}
{{ toYaml .Values.fbuilder.container.extraEnvs | indent 12 }}
{{- end }}
          ports:
           - containerPort: {{ .Values.fbuilder.container.port}}
          imagePullPolicy: {{ .Values.fbuilder.image.pullPolicy}}
          volumeMounts:
            - name: tz
              mountPath: /etc/localtime

        - name: motebus
          image: "{{ .Values.motebus.image.repository }}:{{ .Values.motebus.image.tag }}"
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: MBSTACK_BUSMODE
              value: {{ .Values.MBSTACK_BUSMODE | quote }}
            - name: MBSTACK_UPSTREAM
              value: {{ .Values.MBSTACK_UPSTREAM }}
            - name: MBSTACK_WATCHLEVEL
              value: {{ .Values.MBSTACK_WATCHLEVEL | quote }}
            - name: MBSTACK_BUSNAME
              value: {{ .Values.MBSTACK_BUSNAME }}
            - name: MBSTACK_DATAPATH
              value: {{.Values.MBSTACK_DATAPATH }}
            - name: MBSTACK_IPFINDER
              value: {{ .Values.MBSTACK_IPFINDER | quote }}
          imagePullPolicy: {{ .Values.motebus.image.pullPolicy }}
          volumeMounts:
{{- if .Values.motebus.persistence.enabled}}
            - name: motebus-vol
              mountPath: {{.Values.MBSTACK_DATAPATH}}
{{- end}}
            - name: tz
              mountPath: /etc/localtime
      volumes:
        - name: tz
          hostPath:
            path: /etc/localtime             

  volumeClaimTemplates:
{{- if .Values.motebus.persistence.enabled}}
    - metadata:
        name: motebus-vol
      spec:
        accessModes:  [ {{ .Values.motebus.persistence.accessMode | quote }} ]
        storageClassName: {{ .Values.motebus.persistence.storageClass | quote }}
        resources:
            requests:
                storage: {{ .Values.motebus.persistence.size | quote }}
{{- end}}