apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.fbuilder.service.type }}
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
    - protocol: {{ .Values.fbuilder.service.protocol }}
{{- if eq .Values.fbuilder.service.type "NodePort"}}
      nodePort: {{ .Values.fbuilder.service.nodePort}}
{{- end}}
      port: {{ .Values.fbuilder.service.port}}
      targetPort: {{ .Values.fbuilder.container.port}}
{{- if eq .Values.fbuilder.service.type "ClusterIP"}}
  clusterIP: None
{{- end}}