# replication
replicaCount: 1
# pod node selector
nodeSelector: {}
# pod toleration
tolerations: []
#pod DNS policy and config
podDnsPolicy: "None"
podDnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4
#motechat motebus gateway
MCHAT_MBGWIP: 127.0.0.1
#motechat dc
MCHAT_DC: dc
#motechat ioc
MCHAT_IOC: ioc
# motechat send timeout
MCHAT_SENDTIMEOUT: "6"
# motechat send reply timeout
MCHAT_WAITREPLY: "12"
# motebus bus mode
MBSTACK_BUSMODE: 0
# motebus watch level
MBSTACK_WATCHLEVEL: 3
# motebus bus name
MBSTACK_BUSNAME: webmms
# motebus volume
MBSTACK_DATAPATH: /var/motebus
# motebus upstream
MBSTACK_UPSTREAM: h3.ypcloud.com
# motebus ip finder
MBSTACK_IPFINDER: "auto"
# motebus volume
MBSTACK_DATAPATH: /var/motebus
#timezone
timezone: Asia/Taipei

webmms:
  # image settings and pull policy
  image:
    repository: motebus/webmms-srv
    tag: latest
    pullPolicy: Always
  # service settings
  service:
    type: ClusterIP
    protocol: TCP
    nodePort:
    port: 6000
  # container env settings
  container:
    # iocview port
    port: 6000
    #extra envs
    extraEnvs: {}
  # ingress host and path
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      kubernetes.io/ingress.class: "nginx"
    tls:
      []
      # - hosts:
      #     - myapps.ypcloud.com
      #   secretName: flowbot-tls
    hosts:
      - myapps.ypcloud.com
    path: /webmms/(.*)
    pathType: Prefix

motebus:
  image:
    repository: motebus/motebus
    tag: latest
    pullPolicy: Always
  persistence:
    #Enable config persistence using PVC
    enabled: true
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 1Gi
