kind: StatefulSet
# pod node selector
nodeSelector: {}
# replication
replicaCount: 1
# pod toleration
tolerations: []
#pod DNS policy and config
podDnsPolicy: "None"
podDnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4
timezone: Asia/Taipei

NB_USER: 
NB_TOKEN: 
NB_IP: 0.0.0.0
NB_PORT: 8888
NB_BASE_URL: "/"
JUPYTER_ENABLE_LAB: "yes"
CHOWN_HOME: "yes"
CHOWN_HOME_OPTS: "-R"
GRANT_SUDO: "yes"
RESTARTABLE: "yes"
MLFLOW_S3_ENDPOINT_URL: https://cos.twcc.ai
AWS_ACCESS_KEY_ID: QQV0EC2S038W29QMK1VV
AWS_SECRET_ACCESS_KEY: EDV54sny8Mez1YrIqB5hQpgSNrpMKMFutlQyRhFw
MLFLOW_TRACKING_URI: https://ai-labs.nchc.org.tw/mlflow/3255f1fc9799abeb097b6b7c56bef98a/

jupyter:
  # image settings and pull policy
  image:
    repository: motebus/ibuilder
    tag: v1.0.0
    pullPolicy: Always
  # service settings
  service:
    type: ClusterIP
    protocol: TCP
    nodePort:
    port: 8000
  # container env settings
  container:
    #extra envs
    extraEnvs: {}
    command: 
      - mlflow
      - models
      - serve
      - -m
      - s3://0ea2e731-2a38-46dd-a920-3c97de8c4b43/0/003692cee6fb4d4a86dd161ea7dbeef3/artifacts/wine-model
      - -p
      - 8888
      - -h
      - 0.0.0.0
  # ingress host and path
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "kong"
      konghq.com/strip-path: "true"
    tls:
      []
      # - hosts:
      #     - myapps.ypcloud.com
      #   secretName: flowbot-tls
    hosts:
      - myapps.ypcloud.com
    path: /ibuilder
    pathType: Prefix
  persistence:
    #Enable config persistence using PVC
    enabled: true
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 5Gi