ingress:
  host: myapps.ypcloud.com
  path: /

host:
  path:
    motebus: /var/motebus/
    flowbot: /var/motebus/flow/

pod:
  name: mpod-

container:
    einame:

mbstack:
  upstream: uc.ypcloud.com,boss.ypcloud.com

replicaCount: 1

image:
  repository:
    motebus: motebus/motebus:v2.4.8
    fbuilder: motebus/fbuilder:latest
  pullPolicy: Always

service:
  type: ClusterIP
  protocol: TCP

nodeSelector: {}