enabledHttpsBackendProtocol: false
enabledSslRedirect: false

namespace: default 

ingress:
  host: myapps.ypcloud.com
  path: /fbuilder/

container:
    einame: fbuilder-exmaple
    motebusGateway: 127.0.0.1
    dc: dc
    userMode: "single"
    port: 18880
    storageMode: "cloud"


mbstack:
  upstream: gke.ypcloud.com


replicaCount: 1

image:
  repository:
    motebus: motebus/motebus:v2.4.9
    fbuilder: motebus/fbuilder:v1.4.2
  pullPolicy: 
    motebus: IfNotPresent
    fbuilder: IfNotPresent

service:
  type: ClusterIP
  protocol: TCP
  port: 80

nodeSelector: {}