# pod node selector
nodeSelector: {}
# replication
replicaCount: 1
# pod toleration
tolerations: []
#pod DNS policy and config
podDnsPolicy: "None"
podDnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4
#motechat ei name
MCHAT_EINAME: fbuilder-example
#motechat motebus gateway IP
MCHAT_MBGWIP: 127.0.0.1
#motechat motebus gateway port
MCHAT_MBGWPORT: 6888
#motechat dc
MCHAT_DC: dc
#motechat ioc
MCHAT_IOC: ioc
#motechat send timeout
MCHAT_SENDTIMEOUT: "6"
#motechat send reply timeout
MCHAT_WAITREPLY: "12"
#motechat log level
MCAHT_WATCHLEVEL: 1
#fbuilder user mode, "single, multi"
USER_MODE: single
#fbuilder mode, "local, xstorage, cloud"
STORAGE_MODE: cloud
# motebus upstream
MBSTACK_UPSTREAM: h3.ypcloud.com
# motebus bus mode
MBSTACK_BUSMODE: 0
# motebus watch level
MBSTACK_WATCHLEVEL: 3
# motebus bus name
MBSTACK_BUSNAME:
# motebus volume
MBSTACK_DATAPATH: /var/motebus
# motebus ip finder
MBSTACK_IPFINDER: "auto"
#timezone
timezone: Asia/Taipei

fbuilder:
  # image settings and pull policy
  image:
    repository: motebus/fbuilder
    tag: latest
    pullPolicy: Always
  # service settings
  service:
    type: ClusterIP
    protocol: TCP
    nodePort:
    port: 1880
  # container env settings
  container:
    # cannot change fbuilder port
    port: 18880
    #extra envs
    extraEnvs: {}
  # ingress host and path
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    tls:
      []
      # - hosts:
      #     - myapps.ypcloud.com
      #   secretName: flowbot-tls
    hosts:
      - myapps.ypcloud.com
    path: /fbuilder/(.*)
    pathType: Prefix

motebus:
  image:
    repository: motebus/motebus
    tag: latest
    pullPolicy: Always
  persistence:
    #Enable config persistence using PVC
    enabled: true
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 1Gi
