# nginx-ingress-control annotation ssl redirect
enabledSslRedirect: false

# chart namespace
namespace: default 

# ingress host and path
ingress:
  host: myapps.ypcloud.com
  path: /fbuilder
  pathName: "null"

# container env settings
container:
    # fbuilder port
    port: 18880
    #extra envs
    extraEnvs: {}

# replication
replicaCount: 1

#container image settings and pull policy
image:
  repository:
    motebus: motebus/motebus:latest
    fbuilder: motebus/fbuilder:latest
  pullPolicy: 
    motebus: Always
    fbuilder: Always

# service settings
service:
  type: ClusterIP
  protocol: TCP
  nodePort: 
  port: 80

# pod node selector
nodeSelector: {}

persistence:
    #Enable config persistence using PVC
    enabled: true
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 1Gi

#motechat ei name
MCHAT_EINAME: fbuilder-example
#motechat motebus gateway
MCHAT_MBGWIP: 127.0.0.1
#motechat dc
MCHAT_DC: dc
#fbuilder user mode, "single, multi"
USER_MODE: single
#fbuilder mode, "local, xstorage, cloud"
STORAGE_MODE: cloud
# motebus upstream
MBSTACK_UPSTREAM: gke.ypcloud.com
# motebus bus mode
MBSTACK_BUSMODE: 0
# motebus watch level
MBSTACK_WATCHLEVEL: 3
# motebus bus name
MBSTACK_BUSNAME: 

#timezone
timezone: Asia/Taipei