kind: Deployment
# pod node selector
nodeSelector: {}
# replication
replicaCount: 1
# pod toleration
tolerations: []
#pod DNS policy and config
podDnsPolicy: "None"
podDnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4

NODE_ENV: production
#fbuilder user mode, "single, multi"
USER_MODE: single
#fbuilder mode, "local, xstorage, cloud"
STORAGE_MODE: cloud
# fbuilder project enable
FB_PROJECT_ENABLE: "1"
FB_QOCIMAN: ">p33/qbix/qociman-app"
FB_OBJSTORE: ">svc/objstore"
FB_QMAN_DDN: ">svc/qman"
FB_ACCOUNT_MODE: "sso"
FB_ACCOUNT_URL: "https://account.ypcloud.com/auth/profile"
FB_ACCOUNT_LOGIN: "https://account.ypcloud.com/auth/verify/?ReturnURL=https://flowbuilder.ypcloud.com/auth/strategy/callback"
FB_ACCOUNT_LOGOUT: "https://account.ypcloud.com/auth/logout/?ReturnURL=https://flowbuilder.ypcloud.com"

#motechat dc
MCHAT_DC: dc
#motechat motebus gateway IP
MCHAT_MBGWIP: 127.0.0.1
#motechat motebus gateway port
MCHAT_MBGWPORT: 6888
#motechat appname
MCHAT_APPNAME: fbuilder-example-app
#motechat ei name
MCHAT_EINAME: fbuilder-example
#motechat ioc
MCHAT_IOC: ioc
#motechat send timeout
MCHAT_SENDTIMEOUT: "6"
#motechat send reply timeout
MCHAT_WAITREPLY: "12"
#motechat log level
MCAHT_WATCHLEVEL: 1

#timezone
timezone: Asia/Taipei

fbuilder:
  # image settings and pull policy
  image:
    repository: motebus/fbuilder
    tag: latest
    pullPolicy: Always
  # service settings
  service:
    type: ClusterIP
    protocol: TCP
    nodePort:
    port: 1880
  # container env settings
  container:
    # cannot change fbuilder port
    port: 18880
    #extra envs
    extraEnvs: {}
  # ingress host and path
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "kong"
      konghq.com/strip-path: "true"
      konghq.com/protocols: "https"
      konghq.com/https-redirect-status-code: "301"
#      nginx.ingress.kubernetes.io/rewrite-target: /$1
#      kubernetes.io/ingress.class: "nginx"
#      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    tls:
      []
      # - hosts:
      #     - myapps.ypcloud.com
      #   secretName: flowbot-tls
    hosts:
      - myapps.ypcloud.com
    path: /fbuilder
#    path: /fbuilder/(.*)
    pathType: Prefix
