# nginx-ingress-control annotation ssl redirect
enabledSslRedirect: false

# chart namespace
namespace: default 

# Deployment, StatefulSet
kind: Deployment

# ingress host and path
ingress:
  host: myapps.ypcloud.com
  path: /fbuilder/

# container env settings
container:
    # fbuilder port
    port: 18880
    #extra envs
    extraEnvs: {}

# motebus upstream
mbstack:
  upstream: gke.ypcloud.com

# replication
replicaCount: 1

#container image settings and pull policy
image:
  repository:
    motebus: motebus/motebus:v2.4.9
    fbuilder: motebus/fbuilder:latest
  pullPolicy: 
    motebus: IfNotPresent
    fbuilder: IfNotPresent

# service settings
service:
  type: ClusterIP
  protocol: TCP
  port: 80

# pod node selector
nodeSelector: {}

persistence:
    #Enable config persistence using PVC
    enabled: true
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 1Gi

#motechat ei name
MCHAT_EINAME: fbuilder-example
#motechat motebus gateway
MCHAT_MBGWIP: 127.0.0.1
#motechat dc
MCHAT_DC: dc
#fbuilder user mode
USER_MODE: single
#fbuilder xstorage mode
STORAGE_MODE: xstorage
# motebus upstream
MBSTACK_UPSTREAM: gke.ypcloud.com
# motebus bus mode
MBSTACK_BUSMODE: 0