enabledHttpsBackendProtocol: false
enabledSslRedirect: false

ingress:
  host: myapps.ypcloud.com
  path: /fbuilder/

host:
  path:
    motebus: /var/motebus/
    flowbot: /var/motebus/flow/

container:
    einame:
    motebusGateway: 127.0.0.1
    dc: dc
    userMode: "single"
    port: 18880
    storageMode: "cloud"


mbstack:
  upstream: uc.ypcloud.com,boss.ypcloud.com


replicaCount: 1

image:
  repository:
    motebus: motebus/motebus:v2.4.8
    fbuilder: motebus/fbuilder:latest
  pullPolicy: Always

service:
  type: ClusterIP
  protocol: TCP
  port: 443

nodeSelector: {}