apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector}}
{{- end }}
      containers:
        - name: sscreen
          image: {{ .Values.image.repository.sscreen}}
          env:
            - name: MOTEBUS_GATEWAY
              value: 127.0.0.1
            - name: DC
              value: dc
          ports:
           - name: sscreen-port
             containerPort: 8080
          imagePullPolicy: {{ .Values.image.pullPolicy}}

        - name: motebus
          image: {{ .Values.image.repository.motebus}}
          env:
            - name: MBSTACK_BUSMODE
              value: "0"
            - name: MBSTACK_BUSNAME
              value: mpod
            - name: MBSTACK_UPSTREAM
              value: {{.Values.mbstack.upstream}}
            - name: MBSTACK_ALIASES
              value: {{.Values.mbstack.aliases}}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
            
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port}}
      targetPort: sscreen-port

