{{- if .Values.imodel.ingress.enabled}}
{{- $imodelIngressPath := .Values.imodel.ingress.path -}}
{{- $imodelServicePort := .Values.imodel.service.port -}}
{{- $imodelIngressPathType := .Values.imodel.ingress.pathType -}}
{{- $releaseName := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-imodel
{{- with .Values.imodel.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.imodel.ingress.tls }}
  tls:
{{ toYaml .Values.imodel.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range .Values.imodel.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $imodelIngressPath }}
            pathType: {{ $imodelIngressPathType }}
            backend:
              service:
                name: {{ $releaseName }}-imodel
                port:
                  number: {{ $imodelServicePort }}
  {{- end}}
{{- end}}
---
{{- if .Values.swagger.ingress.enabled}}
{{- $swaggerIngressPath := .Values.swagger.ingress.path -}}
{{- $swaggerServicePort := .Values.swagger.service.port -}}
{{- $swaggerIngressPathType := .Values.swagger.ingress.pathType -}}
{{- $releaseName := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-swagger
{{- with .Values.swagger.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.swagger.ingress.tls }}
  tls:
{{ toYaml .Values.swagger.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range .Values.swagger.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $swaggerIngressPath }}
            pathType: {{ $swaggerIngressPathType }}
            backend:
              service:
                name: {{ $releaseName }}-swagger
                port:
                  number: {{ $swaggerServicePort }}
  {{- end}}
{{- end}}