kind: Deployment
# pod node selector
nodeSelector: {}
# replication
replicaCount: 1
# pod toleration
tolerations: []
#pod DNS policy and config
podDnsPolicy: "None"
podDnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4
timezone: Asia/Taipei

hostName: myapps.ypcloud.com
https: true
ingressClassName: nginx
addSpecIngressClassName: true

## imodel
API_TOKEN:
MLFLOW_S3_ENDPOINT_URL:
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
MODEL_URI:
SWAGGER_ENDPOINT_URL:
SWAGGER_ACCESSKEY:
SWAGGER_SECRETKEY:
SWAGGER_BUCKET:
SWAGGER_OBJECT:

imodel:
  # image settings and pull policy
  image:
    repository: motebus/imodel
    tag: 1.3.5
    pullPolicy: IfNotPresent
  # service settings
  service:
    type: ClusterIP
    protocol: TCP
    nodePort:
    port: 5000
    clusterIP: None
    annotations:
  # container env settings
  container:
    #extra envs
    extraEnvs: {}
    command: []
  # ingress host and path
  ingress:
    enabled: true
    rewritePath: false
    path: /model
  persistence:
    #Enable config persistence using PVC
    enabled: true
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 5Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 3Gi
      cpu: 500m
