# pod node selector
nodeSelector: {}
# replication
replicaCount: 1
# pod toleration
tolerations: []
# pod DNS policy and config

# podDnsPolicy: "None"
# podDnsConfig:
#   nameservers:
#     - 8.8.8.8
#     - 8.8.4.4

# s3 endpoint url
MLFLOW_S3_ENDPOINT_URL: 
# aws acces key
AWS_ACCESS_KEY_ID:
# aws secret key
AWS_SECRET_ACCESS_KEY:
# mysql db uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@127.0.0.1:3306/${MYSQL_DATABASE}
DB_URI: mysql+pymysql://mlflowuser:fKe14EK8aM@127.0.0.1:3306/mlflowdb
# s3 uri "s3://bucket"
ARTIFACT_URI: s3://default

MYSQL_DATABASE: mlflowdb
MYSQL_USER: mlflowuser
MYSQL_PASSWORD: fKe14EK8aM
MYSQL_ROOT_PASSWORD: Mde3nAC5kL
MYSQL_DATAPATH: /var/lib/mysql

mlflow:
  image:
    repository: motebus/mlflow
    tag: v1.0.0
    pullPolicy: Always
  # container env settings
  container:
    #extra envs
    extraEnvs: {}

nginx:
  image:
    repository: motebus/nginx
    tag: v1.0.0
    pullPolicy: Always
  # service settings
  service:
    type: ClusterIP
    protocol: TCP
    nodePort:
    port: 80
  # container env settings
  container:
    #extra envs
    extraEnvs: {}
  # ingress host and path
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "kong"
      konghq.com/strip-path: "true"
    tls:
      []
      # - hosts:
      #     - myapps.ypcloud.com
      #   secretName: mlflow-tls
    hosts:
      - ai-mkt.nchc.org.tw
    path: /mlflow/(.*)
    pathType: Prefix

db:
  image:
    repository: mysql/mysql-server
    tag: 8.0.23
    pullPolicy: Always
  persistence:
    #Enable config persistence using PVC
    enabled: true
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 5Gi
