apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: flowbot
          image: {{ .Values.image.repository.flowbot}}
          env:
            - name: FBOT_FLOWID
              value: {{ .Values.container.flowId | quote}}
            - name: FBOT_EINAME
              value: {{ .Values.container.einame }}
            - name: FBOT_APPNAME
              value: {{ .Values.container.einame }}-app
            - name: FBOT_MODE
              value: {{ .Values.container.mode}}
            - name: MCHAT_MBGWIP
              value: {{ .Values.container.motebusGateway}}
            - name: MCHAT_DC
              value: {{ .Values.container.dc}}
{{- if .Values.ui.enabled }}
            - name: FBOT_UI
              value: "1"
            - name: FBOT_PORT
              value: "1880"
{{- end}}
{{- if .Values.container.extraEnvs }}
{{ toYaml .Values.container.extraEnvs | indent 12 }}
{{- end }}
          ports:
           - name: flowbot-port
             containerPort: 1880
          imagePullPolicy: {{ .Values.image.pullPolicy.flowbot}}
          volumeMounts:
          - name: module-vol
            mountPath: /usr/src/node-red/node_modules/leveldown

        - name: motebus
          image: {{ .Values.image.repository.motebus}}
          env:
            - name: MBSTACK_BUSMODE
              value: "0"
            - name: MBSTACK_BUSNAME
              value: 
            - name: MBSTACK_UPSTREAM
              value: {{.Values.mbstack.upstream}}
          imagePullPolicy: {{ .Values.image.pullPolicy.motebus}}

      volumes:
        - name: module-vol
          hostPath:
            path: {{ .Values.volumes.path}}{{ .Release.Name }}
            type: DirectoryOrCreate

            
---
{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port}}
      targetPort: flowbot-port
{{- end}}