apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: flowbot
          image: {{ .Values.image.repository.flowbot}}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: MCHAT_EINAME
              value: {{ .Values.MCHAT_EINAME }}
            - name: MCHAT_APPNAME
              value: {{ .Values.MCHAT_EINAME }}-app
            - name: MCHAT_MBGWIP
              value: {{ .Values.MCHAT_MBGWIP}}
            - name: MCHAT_MBGWPORT
              value: {{ .Values.MCHAT_MBGWPORT | quote}}
            - name: MCHAT_DC
              value: {{ .Values.MCHAT_DC}}
            - name: FBOT_MODE
              value: {{ .Values.FBOT_MODE}}
            - name: FBOT_FLOWID
              value: {{ .Values.FBOT_FLOWID | quote}}
            - name: FBOT_PORT
              value: {{ .Values.FBOT_PORT | quote }}
            - name: FBOT_UI
              value: {{ .Values.FBOT_UI | quote}}
{{- if .Values.container.extraEnvs }}
{{ toYaml .Values.container.extraEnvs | indent 12 }}
{{- end }}
          ports:
           - name: flowbot-port
             containerPort: {{ .Values.FBOT_PORT }}
          imagePullPolicy: {{ .Values.image.pullPolicy.flowbot}}
          volumeMounts:
            - name: flowbot-tz
              mountPath: /etc/localtime


        - name: motebus
          image: {{ .Values.image.repository.motebus}}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: MBSTACK_BUSMODE
              value: {{ .Values.MBSTACK_BUSMODE | quote}}
            - name: MBSTACK_UPSTREAM
              value: {{.Values.MBSTACK_UPSTREAM}}
          imagePullPolicy: {{ .Values.image.pullPolicy.motebus}}
          volumeMounts:
            - name: motebus-tz
              mountPath: /etc/localtime
    
      volumes:
        - name: flowbot-tz
          hostPath:
            path: /etc/localtime
        - name: motebus-tz
          hostPath:
            path: /etc/localtime

---
{{- if eq .Values.FBOT_UI "1"}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port}}
      targetPort: flowbot-port
{{- end}}