apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: flowbot
          image: {{ .Values.image.repository.flowbot}}
          env:
            - name: EI_NAME
              value: {{ .Values.container.einame }}
            - name: APP_NAME
              value: {{ .Values.container.einame }}-app
            - name: MOTEBUS_GATEWAY
              value: {{ .Values.container.motebusGateway}}
            - name: DC
              value: {{ .Values.container.dc}}
            - name: FLOW_ID
              value: {{ .Values.container.flowID}}
{{- if .Values.ui.enabled }}
            - name: UI_MODE
              value: "1"
            - name: PORT
              value: "1880"
{{- end}}
{{- if .Values.container.extraEnvs }}
{{ toYaml .Values.container.extraEnvs | indent 12 }}
{{- end }}
          ports:
           - name: flowbot-port
             containerPort: {{ .Values.container.port}}
          imagePullPolicy: {{ .Values.image.pullPolicy.flowbot}}

        - name: motebus
          image: {{ .Values.image.repository.motebus}}
          env:
            - name: MBSTACK_BUSMODE
              value: "0"
            - name: MBSTACK_BUSNAME
              value: 
            - name: MBSTACK_UPSTREAM
              value: {{.Values.mbstack.upstream}}
          imagePullPolicy: {{ .Values.image.pullPolicy.motebus}}

            
---
{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port}}
      targetPort: flowbot-port
{{- end}}