{{- if .Values.ingress.enabled}}
{{- $USER_MODE := .Values.USER_MODE -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathName := .Values.ingress.pathName -}}
{{- $servicePort := .Values.service.port -}}
{{- $releaseName := .Release.Name -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: {{ $ingressPathType }}
            backend:
              service:
                name: {{ $releaseName }}
                port:
                  number: {{ $servicePort }}
  {{- end}}
{{- end}}