apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
      # hostNetwork: true
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: flowbot
          image: {{ .Values.image.repository.flowbot}}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: MCHAT_EINAME
              value: {{ .Values.MCHAT_EINAME }}
            - name: MCHAT_APPNAME
              value: {{ .Values.MCHAT_EINAME }}-app
            - name: MCHAT_MBGWIP
              value: {{ .Values.MCHAT_MBGWIP}}
            - name: MCHAT_MBGWPORT
              value: {{ .Values.MCHAT_MBGWPORT | quote}}
            - name: MCHAT_DC
              value: {{ .Values.MCHAT_DC}}
            - name: FBOT_MODE
              value: {{ .Values.FBOT_MODE}}
            - name: FBOT_FLOWID
              value: {{ .Values.FBOT_FLOWID | quote}}
            - name: FBOT_PORT
              value: {{ .Values.FBOT_PORT | quote }}
{{- if .Values.enabledUI }}
            - name: FBOT_UI
              value: {{ .Values.FBOT_UI | quote}}
{{- end}}
{{- if .Values.container.extraEnvs }}
{{ toYaml .Values.container.extraEnvs | indent 12 }}
{{- end }}
          ports:
           - name: flowbot-port
             containerPort: {{ .Values.FBOT_PORT }}
          imagePullPolicy: {{ .Values.image.pullPolicy.flowbot}}
          volumeMounts:
            - name: {{ .Release.Name}}-vol
              mountPath: /usr/src/node-red/flow
            - name: flowbot-tz
              mountPath: /etc/localtime

        - name: motebus
          image: {{ .Values.image.repository.motebus}}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: MBSTACK_BUSMODE
              value: {{.Values.MBSTACK_BUSMODE | quote}}
            - name: MBSTACK_UPSTREAM
              value: {{.Values.MBSTACK_UPSTREAM}}
            - name: MBSTACK_WATCHLEVEL
              value: {{.Values.MBSTACK_WATCHLEVEL | quote}}
            - name: MBSTACK_BUSNAME
              value: {{ .Values.MBSTACK_BUSNAME}}
          imagePullPolicy: {{ .Values.image.pullPolicy.motebus}}
          volumeMounts:
            - name: motebus-tz
              mountPath: /etc/localtime

      volumes:
        - name: flowbot-tz
          hostPath:
            path: /etc/localtime
        - name: motebus-tz
          hostPath:
            path: /etc/localtime    
{{- if not .Values.persistence.enabled }}
        - name: {{ .Release.Name}}-vol
          emptyDir: {}
{{- end }}

{{- if .Values.persistence.enabled}}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name}}-vol
      spec:
        accessModes:  [ {{ .Values.persistence.accessMode | quote }} ]
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
            requests:
                storage: {{ .Values.persistence.size | quote }}
{{- end}}