kind: Deployment
# pod node selector
nodeSelector: {}
# replication
replicaCount: 1
# pod toleration
tolerations: []
#pod DNS policy and config
podDnsPolicy: "None"
podDnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4
timezone: Asia/Taipei

hostName: myapps.ypcloud.com
https: true
ingressClassName: nginx

## imodel
MLFLOW_S3_ENDPOINT_URL:
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
MODEL_URI:
API_TOKEN:
## swagger-autogen
MINIO_S3_BUCKET:
MINIO_S3_OBJECT:
MINIO_S3_ENDPOINT:
MINIO_S3_PORT:
MINIO_S3_USESSL:
MINIO_S3_ACCESSKEY:
MINIO_S3_SECRETKEY:

imodel:
  # image settings and pull policy
  image:
    repository: motebus/imodel
    tag: 1.1.1
    pullPolicy: IfNotPresent
  # service settings
  service:
    type: ClusterIP
    protocol: TCP
    nodePort:
    port: 5000
    clusterIP: None
    annotations:
      konghq.com/plugins: rate-limiting, http-log, key-auth
  # container env settings
  container:
    #extra envs
    extraEnvs: {}
    command: []
  # ingress host and path
  ingress:
    enabled: true
    path: /model
  persistence:
    #Enable config persistence using PVC
    enabled: true
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 5Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 3Gi
      cpu: 500m
swagger:
  enabled: true
  # image settings and pull policy
  image:
    repository: motebus/swagger
    tag: 3.0.1
    pullPolicy: IfNotPresent
  # service settings
  service:
    type: ClusterIP
    protocol: TCP
    nodePort:
    port: 3000
    clusterIP: None
  # container env settings
  container:
    #extra envs
    extraEnvs: {}
    command: []
  ingress:
    enabled: true
    path: /model
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m
