kind: Deployment
# pod node selector
nodeSelector: {}
# replication
replicaCount: 1
# pod toleration
tolerations: []
#pod DNS policy and config
podDnsPolicy: "None"
podDnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4
timezone: Asia/Taipei

hostName: myapps.ypcloud.com
https: true
ingressClassName: nginx

## imodel
APP_NAME:
APP_DESC:
API_TOKEN:
BASE_URL:
S3_ENDPOINT_URL:
S3_ACCESS_KEY_ID:
S3_SECRET_ACCESS_KEY:
MODEL_URI:
IMODEL_VERSION: 1.6.0
INGRESS_PATH: /model
STORAGE_CLASS: csi-cinder
STORAGE_SIZE: 15Gi

imodel:
  # image settings and pull policy
  image:
    repository: motebus/imodel
    pullPolicy: IfNotPresent
  # service settings
  service:
    type: ClusterIP
    protocol: TCP
    nodePort:
    port: 5000
    clusterIP: None
    annotations:
  # container env settings
  container:
    #extra envs
    extraEnvs: {}
    command: []
  # ingress host and path
  ingress:
    enabled: true
    rewritePath: false
  persistence:
    #Enable config persistence using PVC
    enabled: true
    # PVC Access Mode for config volume
    accessMode: ReadWriteOnce
    # PVC Storage Class for config volume
    storageClass: nfs
    # PVC Storage Request for config volume
    size: 15Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 3Gi
      cpu: 500m
