apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- if .Values.podDnsPolicy}}
      dnsPolicy: {{ .Values.podDnsPolicy}}
{{- end}}
{{- if .Values.podDnsConfig}}
      dnsConfig:
{{ toYaml .Values.podDnsConfig | indent 8}}
{{- end}}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: fbots
          image: {{ .Values.fbots.image.repository }}:{{ .Values.fbots.image.tag }}
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: SENDTIMEOUT
              value: {{ .Values.MCHAT_SENDTIMEOUT | quote }}
            - name: WAITREPLY
              value: {{ .Values.MCHAT_WAITREPLY | quote}}
            - name: MCAHT_WATCHLEVEL
              value: {{ .Values.MCAHT_WATCHLEVEL | quote}}
            - name: MCHAT_EINAME
              value: {{ .Values.MCHAT_EINAME }}
            - name: MCHAT_APPNAME
              value: {{ .Values.MCHAT_APPNAME }}
            - name: MCHAT_MBGWIP
              value: {{ .Values.MCHAT_MBGWIP}}
            - name: MCHAT_DC
              value: {{ .Values.MCHAT_DC}}
            - name: MCHAT_IOC
              value: {{ .Values.MCHAT_IOC}}
            - name: MCHAT_UDID
              value: {{ .Values.MCHAT_UDID | quote}}
            - name: FBOT_MODE
              value: {{ .Values.FBOT_MODE}}
            - name: FBOT_QCODE
              value: {{ .Values.FBOT_QCODE}}
            - name: FBOT_QNAME
              value: {{ .Values.FBOT_QNAME}}
            - name: FBOT_MANY
              value: {{ .Values.FBOT_MANY | quote}}
            - name: FBOT_CLUSTER
              value: {{ .Values.FBOT_CLUSTER | quote}}
            - name: FBOT_MULTI
              value: {{ .Values.FBOT_MULTI | quote}}
            - name: FBOT_PORT
              value: {{ .Values.FBOT_PORT | quote}}
{{- if .Values.fbots.container.extraEnvs }}
{{ toYaml .Values.fbots.container.extraEnvs | indent 12 }}
{{- end }}
          ports:
           - containerPort: {{ .Values.fbots.container.port}}
          imagePullPolicy: {{ .Values.fbots.image.pullPolicy}}
          volumeMounts:
{{- if .Values.fbots.persistence.enabled}}
            - name: fbots-vol
              mountPath: /usr/src/node-red/data/{{ .Values.MCHAT_EINAME }}
{{- end}}
            - name: tz
              mountPath: /etc/localtime

        - name: motebus
          image: "{{ .Values.motebus.image.repository }}:{{ .Values.motebus.image.tag }}"
          env:
            - name: TZ
              value: {{ .Values.timezone}}
            - name: MBSTACK_BUSMODE
              value: {{ .Values.MBSTACK_BUSMODE | quote }}
            - name: MBSTACK_UPSTREAM
              value: {{ .Values.MBSTACK_UPSTREAM }}
            - name: MBSTACK_WATCHLEVEL
              value: {{ .Values.MBSTACK_WATCHLEVEL | quote }}
            - name: MBSTACK_BUSNAME
              value: {{ .Values.MBSTACK_BUSNAME }}
            - name: MBSTACK_DATAPATH
              value: {{.Values.MBSTACK_DATAPATH }}
            - name: MBSTACK_IPFINDER
              value: {{ .Values.MBSTACK_IPFINDER | quote }}
          imagePullPolicy: {{ .Values.motebus.image.pullPolicy }}
          volumeMounts:
{{- if .Values.motebus.persistence.enabled}}
            - name: motebus-vol
              mountPath: {{.Values.MBSTACK_DATAPATH}}
{{- end}}
            - name: tz
              mountPath: /etc/localtime
 
      volumes:
        - name: tz  
          hostPath:
            path: /etc/localtime             

  volumeClaimTemplates:
{{- if .Values.fbots.persistence.enabled}}
    - metadata:
        name: fbots-vol
      spec:
        accessModes: [ {{ .Values.fbots.persistence.accessMode | quote }} ]
        storageClassName: {{ .Values.fbots.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.fbots.persistence.size | quote }}
{{- end}}
{{- if .Values.motebus.persistence.enabled}}
    - metadata:
        name: motebus-vol
      spec:
        accessModes:  [ {{ .Values.motebus.persistence.accessMode | quote }} ]
        storageClassName: {{ .Values.motebus.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.motebus.persistence.size | quote }}
{{- end}}