apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-deployment
    spec:
{{- if .Values.podDnsPolicy}}
      dnsPolicy: {{ .Values.podDnsPolicy}}
{{- end}}
{{- if .Values.podDnsConfig}}
      dnsConfig:
{{ toYaml .Values.podDnsConfig | indent 8}}
{{- end}}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: mlflow
          image: {{ .Values.mlflow.image.repository }}:{{ .Values.mlflow.image.tag }}
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: {{ .Values.MLFLOW_S3_ENDPOINT_URL }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.AWS_ACCESS_KEY_ID }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.AWS_SECRET_ACCESS_KEY }}
            - name: DB_URI
              value: {{ .Values.DB_URI }}
            - name: ARTIFACT_URI
              value: {{ .Values.ARTIFACT_URI }}
          command: {{ .Values.container.command}}
          args: {{ .Values.container.args}}
{{- if .Values.mlflow.container.extraEnvs }}
{{ toYaml .Values.mlflow.container.extraEnvs | indent 12 }}
{{- end }}
          imagePullPolicy: {{ .Values.mlflow.image.pullPolicy}}

        - name: nginx
          image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
{{- if .Values.nginx.container.extraEnvs }}
{{ toYaml .Values.nginx.container.extraEnvs | indent 12 }}
{{- end }}
          ports:
           - containerPort: 80
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy}}

        - name: mysql
          image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          env:
            - name: MYSQL_DATABASE
              value: {{.Values.MYSQL_DATABASE | quote}}
            - name: MYSQL_USER
              value: {{ .Values.MYSQL_USER}}
            - name: MYSQL_PASSWORD
              value: {{.Values.MYSQL_PASSWORD}}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.MYSQL_ROOT_PASSWORD | quote }}
          imagePullPolicy: {{ .Values.db.image.pullPolicy}}
          volumeMounts:
            - name: db-vol
              mountPath: {{.Values.MYSQL_DATAPATH}}

  volumeClaimTemplates:
{{- if .Values.db.persistence.enabled}}
    - metadata:
        name: db-vol
      spec:
        accessModes:  [ {{ .Values.db.persistence.accessMode | quote }} ]
        storageClassName: {{ .Values.db.persistence.storageClass | quote }}
        resources:
            requests:
                storage: 5Gi
{{- end}}    